# Generated by Django 6.0.3 on 2026-03-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_analyses_package_analyses_analysis_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='package_name',
        ),
    ]
