# Generated by Django 6.0.3 on 2026-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyses',
            name='package_version',
            field=models.CharField(default='latest', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='package_version',
            field=models.CharField(default='latest', max_length=50),
        ),
    ]
