# Generated by Django 6.0.3 on 2026-03-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_analyses_package_version_package_package_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_analyses', to='webapp.user'),
        ),
    ]
