# Generated by Django 6.0.3 on 2026-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_notification_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyses',
            name='current_step',
            field=models.CharField(default='Starting...', max_length=255),
        ),
        migrations.AddField(
            model_name='analyses',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
