# Generated by Django 6.0.3 on 2026-03-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyses',
            name='package',
        ),
        migrations.AddField(
            model_name='analyses',
            name='analysis_type',
            field=models.CharField(choices=[('callgraph', 'Call Graph'), ('gasket', 'Gasket')], default='callgraph', max_length=20),
        ),
        migrations.AddField(
            model_name='analyses',
            name='package_name',
            field=models.CharField(default='old_analysis', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyses',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
