# Generated by Django 6.0.3 on 2026-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_name_package_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyses',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
