# Generated by Django 6.0.3 on 2026-04-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_analyses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyses',
            name='task_id',
        ),
    ]
