# Generated by Django 6.0.3 on 2026-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_notification_message_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Analysis Notification', max_length=100),
            preserve_default=False,
        ),
    ]
