# Generated by Django 6.0.3 on 2026-04-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.analyses'),
        ),
    ]
